---
- hosts: all

  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      
  - name: install JDK 11
    apt:
      name: openjdk-11-jdk
      state: present    

  - name: install ansible
    apt:
      name: ansible
      state: present

  - name: install python3
    apt:
      name: python3
      state: present
  - name: install php
    apt:
      name: php
      state: present

  - name: install pip3
    apt:
      name: python3-pip
      state: present

  - name: install lxml
    pip:
      name: lxml 

  - name: install unzip
    apt: 
      name: unzip
      state: present

  - name: download the sonarqube community
    unarchive:
      src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.1.0.47736.zip
      dest: /home/ubuntu/
      remote_src: yes

  - name: Change ownership for sonarquebe
    file:
      path: /home/ubuntu/sonarqube-9.1.0.47736
      owner: ubuntu
      group: ubuntu
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory
  
  - name: Ensure bash, OpenSSl, and libssl are the latest versions
    apt: 
      name: 
      - bash
      - openssl
      - libssl-dev
      - libssl-doc
    update_cache: true 
    state: latest
    tags: packages

  - name: Install PostgreSQL
    apt: 
      name: 
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
    update_cache: true 
    state: installed
    tags: packages

  - name: Ensure the PostgreSQL service is running
    service: 
      name: postgresql 
      state: started 
      enabled: yes

  - name: Ensure database is created
    sudo_user: postgres
    postgresql_db: 
      name: {{ db_name }}
      encoding: 'UTF-8'
      lc_collate: 'en_US.UTF-8'
      lc_ctype: 'en_US.UTF-8'
      template: 'template0'
      state: present

  - name: Ensure user has access to the database
    sudo_user: postgres
    postgresql_user: 
      db: {{ db_name }}
      name: {{ db_user }}
      password: {{ db_password }}
      priv: ALL
      state: present

  - name: Ensure user does not have unnecessary privileges
    sudo_user: postgres
    postgresql_user: 
      name: {{ db_user }}
      role_attr_flags: NOSUPERUSER,NOCREATEDB
      state: pr

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download & unarchive
    unarchive:
      src: http://apache.cs.utah.edu/tomcat/tomcat-9/v9.0.53/bin/apache-tomcat-9.0.53.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true
      
  - name: Create  sample directory
    file:
      path: "/opt/tomcat/webapps"
      state: directory
      mode: 0777
    become: true

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: restarted
      enabled: true
      daemon_reload: true

